### ISSUE TITLE
Emails with capital letters

### ISSUE THREAD

**Issue by Be-Like** [AlbertoPdRF/tisn.app#313] opened 2020-10-02 14:46 UTC
**Describe the bug**
I was able to create a user using an email with capital letters, however if I logged out and then tried to log in again (spelling exactly the same), it would give the error message that the email or password was incorrect.

**To Reproduce**

1. Create user using an email that has capital letters.
2. Log out
3. Attempt to log in using same exact email.

**Expected behavior**
Be able to log in.

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome

**Additional context**
Simplest solution would be to lowercase emails before storing them in the db and before logging in when the user submits the log in form.

**Comment by AlbertoPdRF** [comment] 2020-10-03 19:21
Thanks for opening this issue @Be-Like!

I can't reproduce this one, but maybe it's because I didn't get it right. I created an account with `ALBERTO@tisn.app` and could then log into it just right.

Regarding the comment on the additional context section, that should already be the case, as [we are using the `normalizeEmail()` function](https://github.com/Tisn/tisn.app/blob/master/api/routes/validations.js#L48) from [validator.js](https://github.com/validatorjs/validator.js). Maybe it has something to do with the specific email provider you used to test this?

**Comment by Be-Like** [comment] 2020-10-06 18:41
I've been looking at this, and it may be because I was bypassing all the front end JS and creating a user on the backend without any of the validations. 

For example, when I was creating the populate-users script I wasn't lowercasing the email so it was John_Doe@tisn.app. And when I tried to log in it would throw the error.

**Comment by AlbertoPdRF** [comment] 2020-10-06 19:01
Ah, that definitely makes sense! I think that, in such case, we can safely close this issue, because:
1. We'll have to make sure that documents created with the population scripts pass all the validations when adding such scripts
2. There's no other way to create documents bypassing the validations unless done by hand, in which case there's nothing we can really do about it

If I'm missing something, feel free to comment back and I'll reopen the issue 🙂

Thanks for having taken the time to investigate this! 🕵️

**Closed as completed by AlbertoPdRF** 2020-10-06 19:01 UTC
Labels: bug, question, back end
