### ISSUE TITLE
Birth date doesn't update

### ISSUE THREAD

**Issue by roramigator** [AlbertoPdRF/tisn.app#285] opened 2020-09-11 15:05 UTC
**Description**
Birth day field does not change after modifying it. 

**To Reproduce**

1. Go to *Profile Settings*
2. Click on *Edit* icon
3. Change birth date and save 
4. The field hasn't change 

**Expected behavior**
The data saved from the field should update the user profile

**Screenshots**
![Screenshot_20200911-104805_DuckDuckGo.jpg](https://user-images.githubusercontent.com/55143159/92940724-73aa7000-f41d-11ea-8739-5c6b5f551565.jpg)
![Screenshot_20200911-104817_DuckDuckGo.jpg](https://user-images.githubusercontent.com/55143159/92940752-7c02ab00-f41d-11ea-81ad-eea149815ef7.jpg)
![Screenshot_20200911-104826_DuckDuckGo.jpg](https://user-images.githubusercontent.com/55143159/92940770-81f88c00-f41d-11ea-8f89-7a55286008eb.jpg)
![Screenshot_20200911-104834_DuckDuckGo.jpg](https://user-images.githubusercontent.com/55143159/92940780-8624a980-f41d-11ea-8a95-48cf75bacbf6.jpg)

**Smartphone:**

- Device: Samsung SM-A102U
- OS: Android 10 kernel 4.4.177
- Browser: duckduckgo
- Version: 5.63.1

**Comment by AlbertoPdRF** [comment] 2020-09-11 15:21
Hi @roramigator! 👋 Thanks for opening this issue!

I just tried to reproduce this bug both on my computer (Chrome in Ubuntu) and my phone (Chrome in Android) and couldn't. Also, I just checked [your profile](https://tisn.app/users/5f5b85d7d7d1a000171e9596) and the date that appears there is `01/23/1990`, which I think is the one you were trying to update it to, so I'm not sure on what may have been the problem here 😕

**Comment by roramigator** [comment] 2020-09-11 15:37
Interesting, I just tried it on chrome and firefox (both mobile) and the issue remains; allow me to look into it.

**Comment by AlbertoPdRF** [comment] 2020-09-11 15:40
Wow, very interesting indeed! Let's see if we can figure this out 🙂

**Comment by aorelhas** [comment] 2020-09-18 21:15
This bug isn't a bug, since we can update our birthday date. 👍

**Comment by AlbertoPdRF** [comment] 2020-09-19 15:05
Yep, I'm closing the issue! If at some point we can reproduce it, we can always open it again 🙂

**Closed as completed by AlbertoPdRF** 2020-09-19 15:05 UTC
Labels: bug
